export const productos = [
  {
    id: 1,
    name: "Tractor John Deere 6110M",
    category: "Tractores",
    price: "Consultar",
    image: "/john-deere-green-tractor-6110m.jpg",
    features: ["110 HP", "Transmisión PowerQuad", "Cabina con A/C"],
    condition: "Nuevo",
    badge: "Destacado",
  },
  {
    id: 2,
    name: "Sembradora Agrometal MX 23",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-seeder-implement-green.jpg",
    features: ["23 surcos", "Dosificación neumática", "Monitor de siembra"],
    condition: "Nuevo",
    badge: "Nuevo",
  },
  {
    id: 3,
    name: "Tractor Massey Ferguson 4275",
    category: "Tractores",
    price: "$45.000",
    image: "/red-massey-ferguson-tractor-used.jpg",
    features: ["75 HP", "4x4", "1.200 horas"],
    condition: "Usado",
    badge: "Oportunidad",
  },
  {
    id: 4,
    name: "Pulverizadora Apache 3030",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-sprayer-equipment.jpg",
    features: ["3000L", "Barral 24m", "GPS Ready"],
    condition: "Nuevo",
    badge: "Destacado",
  },
  {
    id: 5,
    name: "Tractor John Deere 6110M",
    category: "Tractores",
    price: "Consultar",
    image: "/john-deere-green-tractor-6110m.jpg",
    features: ["110 HP", "Transmisión PowerQuad", "Cabina con A/C"],
    condition: "Nuevo",
    badge: "Destacado",
  },
  {
    id: 6,
    name: "Sembradora Agrometal MX 23",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-seeder-implement-green.jpg",
    features: ["23 surcos", "Dosificación neumática", "Monitor de siembra"],
    condition: "Nuevo",
    badge: "Nuevo",
  },
  {
    id: 7,
    name: "Tractor Massey Ferguson 4275",
    category: "Tractores",
    price: "$45.000",
    image: "/red-massey-ferguson-tractor-used.jpg",
    features: ["75 HP", "4x4", "1.200 horas"],
    condition: "Usado",
    badge: "Oportunidad",
  },
  {
    id: 8,
    name: "Pulverizadora Apache 3030",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-sprayer-equipment.jpg",
    features: ["3000L", "Barral 24m", "GPS Ready"],
    condition: "Nuevo",
    badge: "Destacado",
  },
  {
    id: 9,
    name: "Tractor John Deere 6110M",
    category: "Tractores",
    price: "Consultar",
    image: "/john-deere-green-tractor-6110m.jpg",
    features: ["110 HP", "Transmisión PowerQuad", "Cabina con A/C"],
    condition: "Nuevo",
    badge: "Destacado",
  },
  {
    id: 10,
    name: "Sembradora Agrometal MX 23",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-seeder-implement-green.jpg",
    features: ["23 surcos", "Dosificación neumática", "Monitor de siembra"],
    condition: "Nuevo",
    badge: "Nuevo",
  },
  {
    id: 11,
    name: "Tractor Massey Ferguson 4275",
    category: "Tractores",
    price: "$45.000",
    image: "/red-massey-ferguson-tractor-used.jpg",
    features: ["75 HP", "4x4", "1.200 horas"],
    condition: "Usado",
    badge: "Oportunidad",
  },
  {
    id: 12,
    name: "Pulverizadora Apache 3030",
    category: "Implementos",
    price: "Consultar",
    image: "/agricultural-sprayer-equipment.jpg",
    features: ["3000L", "Barral 24m", "GPS Ready"],
    condition: "Nuevo",
    badge: "Destacado",
  },
]